gcp-bucket-name: bucket-name
gcp-directory-name: directory-name
gcp-storage-url: storage-url

group:
  name: group-name
  email: group-email

spring:
  security:
    filter:
      order: 2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test

  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: localhost
    port: 6379

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100

  mail:
    host: host
    port: port
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true

  jwt:
    secret: secret

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB

  cloud:
    gcp:
      storage:
        credentials:
          location: storage-secret-key


springdoc:
  swagger-ui:
    path: path
    operations-sorter: method
#  version: v1
  paths-to-match: /api/**

server:
  ssl:
    key-store: key-store-path
    key-store-type: PKCS12
    key-store-password: 1234
